import requests as req
from datetime import datetime, timedelta
import calendar
import re
import os
REG_KEY = os.environ['BLS_API_KEY']
BLS_API_ROOT = "https://api.bls.gov/publicAPI/v2/timeseries/data"
START_YEAR = os.getenv('START_YEAR', 2000)
END_YEAR = datetime.now().year


def consumer_price_index_midwest_monthly(return_latest: bool = False) -> dict:
    api_call = __get_bls_data('CUUR0200SA0')
    return [

        {
            'value': row['value'],
            'date': __get_row_datetime(row),
            'type': 'Annual' if row['periodName'] == 'Annual' else 'Monthly'
        }

        for row in api_call
        if not return_latest or (return_latest and row.get('latest', None))
    ]


def consumer_price_index_midwest_half(return_latest: bool = False) -> dict:
    api_call = __get_bls_data('CUUS0200SA0')
    return [

        {
            'value': row['value'],
            'date': __get_half_datetime(row),
            'type': 'Semi-Annual'
        }

        for row in api_call
        if not return_latest or (return_latest and row.get('latest', None))
    ]


def __get_bls_data(report_id: str):
    data = {'registrationkey': REG_KEY, 'seriesid': report_id, 'startyear': START_YEAR, 'endyear': END_YEAR}
    api_call = req.post(url=BLS_API_ROOT, data=data)
    data = api_call.json()
    time_series_data = data['Results']['series'][0]['data']

    if not time_series_data:
        raise ValueError(data['message'][0])
    return time_series_data


def __get_row_datetime(row) -> datetime:
    """
    :param row: a dict generated by the BLS api.
    :return: the last day of the month supplied in the period key.
    if the period is M13 (annual) then we return end of year
    """

    year = int(row['year'])
    month_period = row['period']
    month_int = __strip_int_from_str(month_period)

    if month_int <= 12:
        return __end_of_month(year, month_int)
    return datetime(year=year, month=12, day=31)


def __get_half_datetime(row) -> datetime:

    year = int(row['year'])
    month, day = (6, 30) if row['period'] == 'S01' else (12, 31)
    return datetime(year=year, month=month, day=day)


def __strip_int_from_str(s: str) -> int:
    return int(re.sub(r'[^0-9]', '', s))


def __end_of_month(year: int, month: int) -> int:
    return datetime(
        year=year,
        month=month,
        day=calendar.monthrange(year, month)[1]
    )